project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Diego P.F. Trindade"
  google-analytics: UA-143198225-1
  navbar:
    left:
      
      - href: about/index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
      - href: publications/index.qmd
        text: Publications
      
page-footer:
    left: "© 2022 Diego Trindade"
    center: "powered by [quarto](https://quarto.org)"
    
format:
  html:
    theme: 
      - dark
      
    css: styles.css
    toc: true

editor: visual




