project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Diego P.F. Trindade"
  google-analytics: UA-143198225-1
  cookie-consent: true

  navbar:
    background: black
    pinned: true
    left:
      
      - href: about/index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
      - href: publications/index.qmd
        text: Publications
      - href: presentations/index.qmd
        text: Presentations
      - href: CV/index.qmd
        text: CV
        
      
page-footer:
    left: "© 2022 Diego Trindade"
    center: "powered by [quarto](https://quarto.org)"
    
format:
  html:
    theme: 
    - dark
    - darkly
      
    css: custom.css
    toc: true

editor: visual



