[[plugins]]
package = "@quarto/netlify-plugin-quarto"

[[redirects]]
  from = "/post/data-wrangling-in-ecology/"
  to = "/posts/rstats/data_wrangling/"
  status = 301
  force = true
  
[[redirects]]
  from = "/post/data-visualization-in-ecology/"
  to = "/posts/rstats/data_viz/"
  status = 301
  force = true