+++
title = "Distribuição espacial de cupins em uma área de Caatinga"
date = "2019-06-13"

authors = ["LS Reis, MMRP Dias, DPF Trindade, CM Knolchelmann, PHA Sena & FPL Melo"]

# Publication type.
# Legend:
# 0 = Uncategorized
# 1 = Conference proceedings
# 2 = Journal
# 3 = Work in progress
# 4 = Technical report
# 5 = Book
# 6 = Book chapter
publication_types = ["6"]

# Publication name and optional abbreviated version.
publication = "In *Ecologia e Conservação da Caatinga curso de campo 2015 (eds. FFS Siqueira et al.). Recife: UFPE*."
publication_short = ""

# Abstract and optional shortened version.
abstract = "Uma população é composta por indivíduos de uma mesma espécie que apresentam uma necessidade semelhante de recursos para sobreviver, crescer e se reproduzir. A disponibilidade de recursos pode determinar padrões de distribuição da população. Para animais com comportamento social, como os cupins, a competição intraespecífica pode alterar a estabilidade da colônia. Nossa hipótese propõe que a competição estabelecerá a distribuição espacial dos cupinzeiros. Estabelecemos uma área de 300 m<sup>2</sup> onde todos os cupinzeiros ativos foram amostrados e tiveram altura e perímetro medidos para posterior cálculo do volume. Para avaliar a distância entre os cupins na área amostrada aplicamos o método da distância euclidiana; para a frequência dos cupinzeiros o método de aproximação quadrática e a frequência esperada de cupinzeiros foi gerada pela distribuição de Poisson para posterior análise de qui-quadrado. Na área estudada, foram amostrados 37 cupinzeiros ativos com distribuição aleatória, não havendo relação entre o tamanho do ninho e a distribuição espacial. A partir disso, sugerimos que a competição não é o fator determinante na distribuição da população estudada. Portanto, a estocasticidade pode estar atuando. Diversos fatores influenciam na distribuição da população de cupins na Caatinga, seus entendimentos podem auxiliar na compreensão do papel dessas populações nos processos ecossistêmicos, bem como a sua distribuição."

abstract_short = ""

# Featured image thumbnail (optional)
image_preview = ""

selected = false

projects = []

# Links (optional).
url_pdf = ""
url_preprint = ""
url_code = ""
url_dataset = ""
url_project = ""
url_slides = ""
url_video = ""
url_poster = ""
url_source = ""

url_custom = []

# Does the content use math formatting?
math = true

# Does the content use source code highlighting?
highlight = true

[header]
image = ""
caption = ""

+++
