+++
title = "Demanda conflitante: reproduzir-se ou defender-se?"
date = "2019-06-13"

authors = ["CMC Rocha, CES Dalotto, DPF Trindade, GS Souza, M Delgado-Jaramillo & JD Ribeiro-Neto"]

# Publication type.
# Legend:
# 0 = Uncategorized
# 1 = Conference proceedings
# 2 = Journal
# 3 = Work in progress
# 4 = Technical report
# 5 = Book
# 6 = Book chapter
publication_types = ["6"]

# Publication name and optional abbreviated version.
publication = "In *Ecologia e Conservação da Caatinga curso de campo 2015 (eds. FFS Siqueira et al.). Recife: UFPE*."
publication_short = ""

# Abstract and optional shortened version.
abstract = "As plantas apresentam mecanismos para evitar herbivoria que podem ser direcionados por demandas fisiológicas conflitantes. A hipótese da disponibilidade de recursos sugere que espécies vegetais investem energia preferencialmente na defesa contra herbivoria e que isso dependente de fatores específicos, como a taxa de crescimento e a disponibilidade de nutrientes no solo. O objetivo do estudo foi investigar se a espécie Senna cana investe diferencialmente na proteção de ramos reprodutivos. O estudo foi desenvolvido no Parque Nacional do Catimbau, onde foram selecionados 10 indivíduos de S. canna e amostrados oito módulos de cada um - quatro ramos frutificados e quatro ramos sem frutos. Foi medida a porcentagem de herbivoria nas três folhas mais distais de cada ramo e contadas o número de sementes sadias e abortadas por fruto destes ramos. Foram obtidos os valores de (1) proporção média de herbivoria nos ramos sem frutos, (2) nos ramos com frutos a média de sementes abortadas por ramo, (3) no indivíduo a herbivoria total do indivíduo e (4) a proporção média de abortos por indivíduo. Os ramos sem frutos sofreram mais herbivoria, o que indica um direcionamento de energia para poupar os mesmos e porcentagem média da herbivoria por ramos com frutos não induziu a uma maior proporção média de sementes abortadas por ramo."

abstract_short = ""

# Featured image thumbnail (optional)
image_preview = ""

selected = false

projects = []

# Links (optional).
url_pdf = ""
url_preprint = ""
url_code = ""
url_dataset = ""
url_project = ""
url_slides = ""
url_video = ""
url_poster = ""
url_source = ""

url_custom = []

# Does the content use math formatting?
math = true

# Does the content use source code highlighting?
highlight = true

[header]
image = ""
caption = ""

+++
