---
title: "A lazy blog almost never updated"
page-layout: custom
css: index.css
listing:
  - id: publications	
    max-description-length: 500
    contents: ../publications/published-papers/**/index.qmd
    sort: "date desc"
    type: default
    categories: false
    max-items: 3
  - id: posts
    max-description-length: 500
    contents: ../posts/rstats/**/index.qmd
    sort: "date desc"
    type: default
    categories: false
    max-items: 3
    
title-block-banner: true
---

I'm a PhD candidate at the University of Tartu, Estonia. My PhD studies focus on understanding how global changes affect species gains and losses (biodiversity change) across space and time. In order to understand those changes, in a spatiotemporal context, I'm assessing how both observed and dark diversity dynamics are changing over time (the latter defined as "currently absent species that could potentially inhabit a study site"). With dark diversity, it is possible to decompose species gains and losses into two space‐related components: one associated with local dynamics (species moving from observed to dark diversity and vice versa) and another related to gains and losses of site‐specific species pool (species moving to and from the pool after regional immigration, regional extinction or change in local ecological conditions). This decomposition might improve the way we detect biodiversity change and disequilibrium dynamics (e.g. extinction debt and colonization credit). To apply and test those ideas I'm using mechanistic models, multi-taxa and long-term databases (plants, birds, lichens, pollen etc.).

::: {style="text-align: center"}
## Education
:::

University of Tartu \| Estonia PhD student \| Sept 2017 - Current

Universidade Federal de Pernambuco \| Brazil Masters in Plant Ecology \| 2015 - 2017

::: {style="text-align: center"}
## Publications
:::

::: {#publications}
:::

::: {style="text-align: right"}
[See All →](../publications)
:::

::: {style="text-align: center"}
## Posts
:::

::: {#posts}
:::

::: {style="text-align: right"}
[See All →](../posts)
:::
